
package br.unisc.video_locadora.Panels;

import br.unisc.video_locadora.Classes.Filmes;
import br.unisc.video_locadora.Classes.Funcionario;
import br.unisc.video_locadora.controll.GeradorDeGrafico;
import com.sun.org.apache.bcel.internal.generic.F2D;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;



public class Funcionario_GERARGRAFICO extends javax.swing.JPanel {


    List<GeradorDeGrafico> graf;
    
    public Funcionario_GERARGRAFICO() {
        initComponents();
        setSize(300, 200);
        
    }
    
    private CategoryDataset createDataset() {
        List<Filmes> lista;
        Funcionario f = new Funcionario();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        lista = f.buscaFilme("");
        graf = f.grafico(lista);
        for(GeradorDeGrafico gr : graf){
            dataset.addValue(gr.getQtd(), gr.getGenero(), gr.getGenero());
        }
        

        return dataset;
    }
    
    public void criaGrafico() {
        CategoryDataset cds = createDataset();
        String titulo = "CineMix";
        String eixoy = "Quantidade";
        String txt_legenda = "Gênero:";
        boolean legenda = true;
        boolean tooltips = true;
        boolean urls = true;
        JFreeChart graf = ChartFactory.createBarChart3D(titulo, txt_legenda, eixoy, cds, PlotOrientation.VERTICAL, legenda, tooltips, urls);
        ChartPanel myChartPanel = new ChartPanel(graf, true);
        myChartPanel.setSize(pnlGrafico.getWidth(), pnlGrafico.getHeight());
        myChartPanel.setVisible(true);
        pnlGrafico.removeAll();
        pnlGrafico.add(myChartPanel);
        pnlGrafico.revalidate();
        pnlGrafico.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrafico = new javax.swing.JPanel();

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlGrafico;
    // End of variables declaration//GEN-END:variables
}
