/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unisc.video_locadora.Panels;

import br.unisc.video_locadora.Classes.Filmes;
import br.unisc.video_locadora.Classes.Funcionario;
import br.unisc.video_locadora.controll.Share;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josej
 */
public class Funcionario_SEARCHMOVIE extends javax.swing.JPanel {

    List<Filmes> lista;

    public Funcionario_SEARCHMOVIE() {
        initComponents();
        ListSelectionModel sel = Tabela.getSelectionModel();
        sel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        sel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (Tabela.getSelectedRow() > -1) {
                    int linha = Tabela.getSelectedRow();
                    String id = Tabela.getModel().getValueAt(linha, 0).toString();
                    String titulo = Tabela.getModel().getValueAt(linha, 1).toString();
                    String ano = Tabela.getModel().getValueAt(linha, 2).toString();
                    String diretor = Tabela.getModel().getValueAt(linha, 3).toString();
                    String genero = Tabela.getModel().getValueAt(linha, 4).toString();
                    String linguagem = Tabela.getModel().getValueAt(linha, 5).toString();
                    String locado = Tabela.getModel().getValueAt(linha, 6).toString();
                    Share.idFilme = Integer.parseInt(id);
                    Share.titulo = titulo;
                    Share.ano = ano;
                    Share.diretor = diretor;
                    Share.genero = genero;
                    Share.linguagem = linguagem;
                    Share.locado = locado;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtBuscar = new javax.swing.JButton();
        BtClose = new javax.swing.JButton();
        TextConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        BtClose.setText("Fechar");
        BtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCloseActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jLabel1.setText("Pesquisar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtClose))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtBuscar)
                    .addComponent(BtClose)
                    .addComponent(TextConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BtCloseActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        String valor = TextConsulta.getText();
        Funcionario f = new Funcionario();
        lista = f.buscaFilme(valor);
        String[] col = {"Id", "Titulo", "Ano", "Diretor", "Gênero", "Linguagem", "Locado"};
        DefaultTableModel modelo = new DefaultTableModel(col, 0);
        for (Filmes p : lista) {
            modelo.addRow(new String[]{String.valueOf(p.getId()), p.getTitulo(), String.valueOf(p.getAno()),
                p.getDiretor(), p.getGenero(), p.getIdioma(), p.getLocado()});
        }
        Tabela.setModel(modelo);
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        try {
            int linha = Tabela.getSelectedRow();
            String id = Tabela.getModel().getValueAt(linha, 0).toString();
            String titulo = Tabela.getModel().getValueAt(linha, 1).toString();
            String ano = Tabela.getModel().getValueAt(linha, 2).toString();
            String diretor = Tabela.getModel().getValueAt(linha, 3).toString();
            String genero = Tabela.getModel().getValueAt(linha, 4).toString();
            String linguagem = Tabela.getModel().getValueAt(linha, 5).toString();
            String locado = Tabela.getModel().getValueAt(linha, 6).toString();

            Share.idFilme = Integer.parseInt(id);
            Share.titulo = titulo;
            Share.ano = ano;
            Share.diretor = diretor;
            Share.genero = genero;
            Share.linguagem = linguagem;
            Share.locado = locado;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "linha inválida!");
        }
    }//GEN-LAST:event_TabelaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtClose;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField TextConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
